// <auto-generated />
using EntityFrameWork.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameWork.Migrations
{
    [DbContext(typeof(BilContext))]
    [Migration("20260310104011_AddReservedel")]
    partial class AddReservedel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BilReservedel", b =>
                {
                    b.Property<int>("BilerBilId")
                        .HasColumnType("int");

                    b.Property<int>("ReservedeleReservedelId")
                        .HasColumnType("int");

                    b.HasKey("BilerBilId", "ReservedeleReservedelId");

                    b.HasIndex("ReservedeleReservedelId");

                    b.ToTable("BilReservedel");
                });

            modelBuilder.Entity("EntityFrameWork.Bil", b =>
                {
                    b.Property<int>("BilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BilId"));

                    b.Property<int>("EjerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("BilId");

                    b.HasIndex("EjerId");

                    b.ToTable("Biler");

                    b.HasData(
                        new
                        {
                            BilId = -1,
                            EjerId = 1,
                            Name = "Ford",
                            Weight = 1400
                        });
                });

            modelBuilder.Entity("EntityFrameWork.Ejer", b =>
                {
                    b.Property<int>("EjerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EjerId"));

                    b.Property<string>("ForNavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EjerId");

                    b.ToTable("Ejere");

                    b.HasData(
                        new
                        {
                            EjerId = 1,
                            ForNavn = "Katrine",
                            SurName = "H"
                        });
                });

            modelBuilder.Entity("EntityFrameWork.Reservedel", b =>
                {
                    b.Property<int>("ReservedelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservedelId"));

                    b.Property<string>("Mærke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReservedelId");

                    b.ToTable("Reservedel");
                });

            modelBuilder.Entity("BilReservedel", b =>
                {
                    b.HasOne("EntityFrameWork.Bil", null)
                        .WithMany()
                        .HasForeignKey("BilerBilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameWork.Reservedel", null)
                        .WithMany()
                        .HasForeignKey("ReservedeleReservedelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFrameWork.Bil", b =>
                {
                    b.HasOne("EntityFrameWork.Ejer", "Ejer")
                        .WithMany("Biler")
                        .HasForeignKey("EjerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejer");
                });

            modelBuilder.Entity("EntityFrameWork.Ejer", b =>
                {
                    b.Navigation("Biler");
                });
#pragma warning restore 612, 618
        }
    }
}
